version: "3.5"

services:
  wireguard:
    image: weejewel/wg-easy
    network_mode: "bridge"
    container_name: wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./wg:/etc/wireguard
    environment:
      - WG_HOST=77.164.136.1
      - PASSWORD=pass
    restart: always
